os: linux
language: csharp
solution: SharpPaste.sln
mono:
 - latest
 - 5.4.0
 - 5.2.0
 - 5.0.1
 - 4.8.1
 - 4.6.2
 - 4.4.2
#deploy:
#  - provider: script
#    script: ./Deployment/develop.sh
#    on:
#      branch: develop
#  - provider: script
#    script: ./Deployment/master.sh
#    on:
#      branch: master
