os: linux
language: csharp
solution: SharpPaste.sln
mono:
 - latest
 - 5.4.0
 - 5.2.0
 - 5.0.1
 - 4.8.1
 - 4.6.2
 - 4.4.2
sudo: required
before_install:
 - sudo apt-get clean
 - sudo apt-get update
deploy:
  - provider: script
    script: deploy.sh develop
    on:
      branch: develop
  - provider: script
    script: deploy.sh master
    on:
      branch: master
