language: csharp
solution: SharpPaste.sln
sudo: required
mono:
 - latest
 - 4.8.0
 - 4.6.2
 - 4.4.2
 - 4.2.3
 - 4.0.4
 - 3.12.1
os:
 - linux
 - osx
before_install:
 - sudo apt-get clean
 - sudo apt-get update
